version: "3.8"

services:
  webui:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - webui-data:/home/hermeswebui/.hermes
    environment:
      - HERMES_WEBUI_HOST=0.0.0.0
      - HERMES_WEBUI_PORT=8787
      - HERMES_WEBUI_STATE_DIR=/home/hermeswebui/.hermes/webui
      - HERMES_AGENT_URL=http://hermesstack-hermesagent-1qi1ft:8642
      - HERMES_WEBUI_PASSWORD=${HERMES_WEBUI_PASSWORD}
      - HERMES_SKIP_CHMOD=1
    networks:
      - dokploy-network

volumes:
  webui-data:
    driver: local

networks:
  dokploy-network:
    external: true
